export default DATA = [
  {
    id: Math.random(),
    title: "Shopee",
    img: require("../assets/images/shop.png"),
    date: "March 12",
    amount: "1,500",
  },
  {
    id: Math.random(),
    title: "PlayStation",
    img: require("../assets/images/ps.png"),
    date: "April 10",
    amount: "2,500",
  },
  {
    id: Math.random(),
    title: "Lazada",
    img: require("../assets/images/lazada.png"),
    date: "April 5",
    amount: "300",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
  {
    id: Math.random(),
    title: "Bit Coin",
    img: require("../assets/images/bitcoin.png"),
    date: "March 23",
    amount: "2,000",
  },
];
